title: XebiaLabs documentation
tagline: 'Deliver faster'
description: 'Leading provider of Continuous Delivery tooling with agentless application release and deployment automation solutions for the Enterprise.'
url: https://docs.xebialabs.com
repo: https://github.com/xebialabs/online-docs-jekyll/edit/master/

sitemap:
    exclude:
        - "/tags-and-subjects.html"
        - "/topic-weights.html"
        - "/xl-deploy/in-product-help.html"

defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "page"

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

jira_dashboard:
  generate: true
  data_file: '' # '_data/development_status.yaml' # use for testing purposes
  dir: 'tracker'
  jira_url: 'https://xebialabs.atlassian.net/rest/api/2'
  jira_username: 'xl-ci'
  jira_password: '8ace886bbe7e'
