title: XebiaLabs documentation
tagline: 'Deliver faster'
description: 'Leading provider of Continuous Delivery tooling with agentless application release and deployment automation solutions for the Enterprise.'
name: XebiaLabs Tips and Tricks Blog
blogurl: http://localhost:4000/tips-and-tricks
author:
  name: XebiaLabs, Inc.
  email: info@xebialabs.com
permalink: /tips-and-tricks/:categories/:year:month:day-:title

paginate: 10
paginate_path: "tips-and-tricks/page:num"

defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "page"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

asciidoc: asciidoctor
asciidoc_ext: "asciidoc,adoc,ad"
asciidoctor:
  safe: safe
  attributes:
    - notitle!
    - hardbreaks
    - idprefix=
    - idseparator=-
    - linkattrs

jira_dashboard:
  generate: true
  data_file: '' # '_data/development_status.yaml' # use for testing purposes
  dir: 'development-dashboard'
  jira_url: 'https://xebialabs.atlassian.net/rest/api/2'
  jira_username: 'xl-ci'
  jira_password: '8ace886bbe7e'


