title: XebiaLabs documentation
tagline: 'Deliver faster'
description: 'Leading provider of Continuous Delivery tooling with agentless application release and deployment automation solutions for the Enterprise.'
url: https://docs.xebialabs.com

sitemap:
    exclude:
        - "/tags-and-subjects.html"

defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "page"

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

asciidoc: asciidoctor
asciidoc_ext: "asciidoc,adoc,ad"
asciidoctor:
  safe: safe
  attributes:
    - notitle!
    - hardbreaks
    - idprefix=
    - idseparator=-
    - linkattrs

jira_dashboard:
  generate: false
  data_file: '' # '_data/development_status.yaml' # use for testing purposes
  dir: 'development-dashboard'
  jira_url: 'https://xebialabs.atlassian.net/rest/api/2'
  jira_username: 'xl-ci'
  jira_password: '8ace886bbe7e'


