highlighter: pygments
permalink: /:categories/:title

defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "page"

title: XebiaLabs documentation
tagline: 'Deliver faster'
description:    ''
site: http://localhost:4000
baseurl:    '/'

author:
  name:           'XebiaLabs'
  url:            http://docs.xebialabs.com
