title: XebiaLabs documentation
tagline: 'Deliver faster'
description: 'Leading provider of Continuous Delivery tooling with agentless application release and deployment automation solutions for the Enterprise.'
url: https://docs.xebialabs.com
twitter:
  username: xebialabs
logo: /images/logos/xebialabs-standard.png
repo: https://github.com/xebialabs/online-docs-jekyll/edit/master/

sitemap:
    exclude:
        - "/tags-and-subjects.html"
        - "/topic-weights.html"
        - "/xl-deploy/in-product-help.html"
        - "/navigation-beta/index.html"
        - "/navigation-beta/xl-deploy/applications-and-environments/dictionaries.html"
        - "/navigation-beta/xl-release/templates/phases-and-tasks.html"
        - "/navigation-beta/xl-testview/customize/custom-reports.html"

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

kramdown:
  input: GFM # Make Jekyll recognize GitHub Flavored Markdown

gems:
  - jekyll-seo-tag

jira_dashboard:
  generate: true
  data_file: '' # '_data/development_status.yaml' use for testing purposes
  dir: 'tracker'
  jira_url: 'https://xebialabs.atlassian.net/rest/api/2'
  jira_username: 'xl-ci'
  jira_password: '8ace886bbe7e'

defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "page"
    -
        scope:
            path: "xl-deploy/how-to"
            type: "pages"
        values:
            layout: "topic"
    -
        scope:
            path: "xl-deploy/concept"
            type: "pages"
        values:
            layout: "topic"
    -
        scope:
            path: "xl-release/how-to"
            type: "pages"
        values:
            layout: "topic"
    -
        scope:
            path: "xl-release/concept"
            type: "pages"
        values:
            layout: "topic"
    -
        scope:
            path: "xl-testview/how-to"
            type: "pages"
        values:
            layout: "topic"
    -
        scope:
            path: "xl-testview/concept"
            type: "pages"
        values:
            layout: "topic"
    -
        scope:
            path: "navigation-beta"
            type: "pages"
        values:
            layout: "navigation-beta-layout"
