title: XebiaLabs documentation
tagline: 'Intelligence and Automation for Enterprise DevOps'
description: 'XebiaLabs develops enterprise-scale Continuous Delivery and DevOps software.'
url: https://docs.xebialabs.com
baseurl: /
twitter:
  username: xebialabs
logo: /images/logos/xebialabs-standard.jpg
repo: https://github.com/xebialabs/online-docs-jekyll/edit/master/

sitemap:
    exclude:
        - "/tags-and-subjects.html"
        - "/topic-weights.html"
        - "/xl-deploy/in-product-help.html"
        - "/navigation-beta/index.html"
        - "/navigation-beta/xl-deploy/applications-and-environments/dictionaries.html"
        - "/navigation-beta/xl-release/templates/phases-and-tasks.html"
        - "/navigation-beta/xl-testview/customize/custom-reports.html"

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

exclude:
    - gradle*
    - build.gradle
    - README.md
    - sources.yml
    - Dockerfile
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock

kramdown:
  input: GFM # Make Jekyll recognize GitHub Flavored Markdown

plugins:
  - jekyll-seo-tag
  - jekyll-asciidoc

jira_dashboard:
  generate: true
  data_file: '' # '_data/development_status.yaml' use for testing purposes
  dir: 'tracker'
  jira_url: 'https://xebialabs.atlassian.net/rest/api/2'
  jira_username: 'documentation@xebialabs.com'
  jira_password: '18docs_ci1313#'

asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - source-highlighter=coderay
    - icons=font

defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "topic"
    -
        scope:
            path: "xl-deploy"
            type: "pages"
        values:
            layout: "topic-xld"
    -
        scope:
            path: "xl-release"
            type: "pages"
        values:
            layout: "topic-xlr"
    -
        scope:
            path: "xl-impact"
            type: "pages"
        values:
            layout: "topic-xli"

    -
        scope:
            path: "xl-impact/"
            type: "pages"
        values:
            layout: "topic-xli"
    -
        scope:
            path: "xl-testview/how-to"
            type: "pages"
        values:
            layout: "topic"
    -
        scope:
            path: "xl-testview/concept"
            type: "pages"
        values:
            layout: "topic"
    -
        scope:
            path: "navigation-beta"
            type: "pages"
        values:
            layout: "navigation-beta-layout"
    -
        scope:
            path: "xl-platform/how-to"
            type: "pages"
        values:
            layout: "topic"
    -
        scope:
            path: "xl-platform/concept"
            type: "pages"
        values:
            layout: "topic"
