title: XebiaLabs documentation
tagline: 'Deliver faster'
description: 'Leading provider of Continuous Delivery tooling with agentless application release & deployment automation solutions for the Enterprise.'
permalink: /:title

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "page"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"

asciidoc: asciidoctor
asciidoc_ext: "asciidoc,adoc,ad"
asciidoctor:
  safe: safe
  attributes:
    - notitle!
    - hardbreaks
    - idprefix=
    - idseparator=-
    - linkattrs
