title: XebiaLabs documentation
tagline: 'Deliver faster'
description: 'Leading provider of Continuous Delivery tooling with agentless application release & deployment automation solutions for the Enterprise.'
url: http://localhost:4000
baseurl: '/'
permalink: /:title

defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "page"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"

asciidoc: asciidoctor
asciidoc_ext: asciidoc,adoc,ad
asciidoctor:
  safe: safe
  attributes:
    - notitle!
    - hardbreaks
    - idprefix=
    - idseparator=-
    - linkattrs
