- name: XL Deploy
  id: xl-deploy
  versions:
    - 3.9.x
    - 4.0.x
    - 4.5.x
- name: XL Release
  id: xl-release
  versions:
    - 4.0.x
    - 3.0.x
- name: XL Scale
  id: xl-scale
  versions:
    - 4.0.x
- name: XL Test
  id: xl-test
  versions:
    - 1.2.x