- name: XL Platform
  id: xl-platform
  blurb: The XebiaLabs suite of products provides lightweight, plug-and-play delivery automation modules for deployment, environment provisioning, Agile test management, and release coordination to help enterprises deliver higher quality software faster.
- name: XL Deploy
  id: xl-deploy
  blurb: <a href="https://xebialabs.com/products/xl-deploy/">XL Deploy</a> is the only application release automation solution that is agentless across all target platforms. Connect to Windows and Unix target systems using proven, industry-standard remote protocols; no agent installation and maintenance, no overhead on the target systems, no firewall ports to be opened, and no security reviews.
  key-concepts-link: /xl-deploy/concept/key-xl-deploy-concepts.html
  installation-link: /xl-deploy/how-to/install-xl-deploy.html
  versions:
    - 8.1.x
    - 8.0.x
    - 7.5.x
    - 7.0.x
- name: XL Release
  id: xl-release
  blurb: XL Release is an end-to-end pipeline orchestration tool for Continuous Delivery and DevOps teams. It handles automated tasks, manual tasks, and complex dependencies and release trains. And XL Release is designed to integrate with your change and release management tools.
  key-concepts-link: /xl-release/concept/core-concepts-of-xl-release.html
  installation-link: /xl-release/how-to/install-xl-release.html
  versions:
    - 8.1.x
    - 8.0.x
    - 7.5.x
    - 7.0.x
- name: XL Impact
  id: xl-impact
  blurb: The first goal-based DevOps Intelligence solution, XL Impact delivers integrated KPIs to show the health of your Continuous Delivery pipeline. It combines DevOps best practices with historical analysis, machine learning, and data from across your tool chain to show trends, predict outcomes, and recommend actions. Use XL Impact to optimize your delivery pipeline, drive ROI, and mitigate risk.
  key-concepts-link: /xl-impact/concept/release-to-customer-filter.html
  installation-link: /xl-impact/how-to/install-xl-impact.html
  versions:
    - 8.1.x
- name: XL TestView
  id: xl-testview
  blurb: XL TestView lets you define, execute, and analyze all of the tests relevant to an application's quality. You can easily manage complex test sets and execute tests across a wide spectrum of tools.
  key-concepts-link: /xl-testview/concept/key-concepts.html
  installation-link: /xl-testview/how-to/install.html
  getting-started-link: /xl-testview/how-to/getting-started.html
  versions:
    - 1.4.x
    - 1.3.x
