- name: XL Platform
  id: xl-platform
  blurb: The XebiaLabs suite of products provides lightweight, plug-and-play delivery automation modules for deployment, environment provisioning, Agile test management, and release coordination to help enterprises deliver higher quality software faster.
- name: XL Deploy
  id: xl-deploy
  blurb: <a href="https://xebialabs.com/products/xl-deploy/">XL Deploy</a> is the only application release automation solution that is agentless across all target platforms. Connect to Windows and Unix target systems using proven, industry-standard remote protocols; no agent installation and maintenance, no overhead on the target systems, no firewall ports to be opened, and no security reviews.
  key-concepts-link: /xl-deploy/concept/key-xl-deploy-concepts.html
  installation-link: /xl-deploy/how-to/install-xl-deploy.html
  versions:
    - 7.2.x
    - 7.0.x
    - 6.0.x
    - 5.5.x
    - 5.1.x
- name: XL Release
  id: xl-release
  blurb: XL Release is an end-to-end pipeline orchestration tool for Continuous Delivery and DevOps teams. It handles automated tasks, manual tasks, and complex dependencies and release trains. And XL Release is designed to integrate with your change and release management tools.
  key-concepts-link: /xl-release/concept/core-concepts-of-xl-release.html
  installation-link: /xl-release/how-to/install-xl-release.html
  versions:
    - 7.2.x
    - 7.0.x
    - 6.0.x
    - 5.0.x
    - 4.8.x
- name: XL Impact
  id: xl-impact
  blurb: XL Impact is the world’s first goal-based team instrument focused on improving your software delivery pipeline and software delivery process. Based on goals and KPI’s it shows the current state of your delivery process and usage of tools. On top of this current state it gives concrete improvement suggestions about where to improve your organisation.
  XL Impact aggregates data from your continuous delivery tools and search’s for patterns to come up with these improvements that make impact on your organisation. After setup, devops managers, and devops teams are typical users of this instrument to discover where to improve. Agile transformation leads and team coaches can use it to determine where to put their effort. Senior executives in organisations can use it to determine the ROI on the budget they spend on transforming their organisation.
  key-concepts-link: /xl-impact/concept/release-to-client-filter.html
  installation-link: /xl-impact/how-to/install-xl-impact.html
  versions:
    - 7.2.x
    - 7.0.x
    - 6.0.x
    - 5.0.x
    - 4.8.x
- name: XL TestView
  id: xl-testview
  blurb: XL TestView lets you define, execute, and analyze all of the tests relevant to an application's quality. You can easily manage complex test sets and execute tests across a wide spectrum of tools.
  key-concepts-link: /xl-testview/concept/key-concepts.html
  installation-link: /xl-testview/how-to/install.html
  getting-started-link: /xl-testview/how-to/getting-started.html
  versions:
    - 1.4.x
    - 1.3.x
